### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [MSMK2/colmar#7]
Grade: Meets expectations

Summary:
Awesome work on this final project! I love your semantic, organized HTML, your use of descriptive `alt` attributes, and that your page is 100% responsive.

A few things to work on would be: 1. using valid attributes, 2. closing elements correctly, and 3. making your CSS even more concise by using group selectors for repeated styles and a single media query per page width.

Next, as a stretch goal, I challenge you to build more pages for this site.  What does a sign in page look like? What about a course page?  Building these extra pages will add some complexity and is a challenge I think you are ready for based on your work here!

**Comment by MSMK2** [comment]
Thanks for the review. Good catches on the attributes and closing elements. I missed them. 

I'm intrigued by your stretch goal as I'm not perfectly clear on best practices for linking pages together and the creation of url slugs. This may be a topic later in the training, but I could use a short tutorial on it. All of the practice examples only have a single page and use "#" for the links. I assume this is pretty easy...just haven't tried it yet.
